
stages:
  - test

test:
  stage: test
  script:
    - unset GOPATH
    - sudo -E /usr/local/go/bin/go test
    - cd cmd/nl
    - go build
    - sudo cp nl /srv/bin/nl
  artifacts:
    paths:
      - cmd/nl/nl
  tags:
    - merge
    - shell
